name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: submodule
      run: git submodule init && git submodule update
    - name: cmake
      run: mkdir build && cd build && cmake --version && cmake ..
    - name: make
      run: cd build && make -j 4
    - name: test
      run: cd build/test && ./gemm && ./conv2d
    - name: test testcases from proj1
      run: cd build/project1/ && ./test1
    - name: test testcases from proj2
      run: cd build/project2/ && ./test2
